### ISSUE TITLE
Error in Sedona object "AlarmDB not found"

### ISSUE THREAD

**Issue by apexc** [automatikas/AlarmDB-EasyIO#14]
Hi, 

I install the latest plugin via CPT plugin method. 
I am also using the latest CPT tool , 22 Dec 2017. 

everything gets deployed nicely and i can see alarm table is created. 
but when i tried to trigger an alarm using the bool alarm object, it tells me "alarmDB not found". 

i did not include the auth_key as this is a local connection and i believe it does not require it. 
anyway, no harm trying, i also insert the auth_key just for testing. it still return the same error.

**Comment by automatikas** [comment]
Hi @apexc 

older release does not support plugin method. 

I pulled new release v.2.07.5

get the latest release and install kit version 1.0.45.24. It will support plugins from now. also update alarmdb folder for the latest bug fixes.

https://github.com/automatikas/AlarmDB-EasyIO/releases/tag/v2.07.5

"alarmDB not found" means that sedona kit can't find file on FG or FS server so if you copied v2.07.4 to plugin folder it will not work as path is not the same in the sedona kit.

You are right about auth_key it is not needed for the same host.

**Comment by apexc** [comment]
Hi @automatikas  , 

Thank you very much for the fast reply.

**Comment by apexc** [comment]
Hi AJ, 

 

Replied too soon.

I am still getting the same error. 

 

But from debug, this is what I get. 

 

GET /sdcard/cpt/plugin/alarmdb/alarmdb_exporter.php?www-command=alarmdb-ping HTTP/1.1

Host: 127.0.0.1

Connection: Keep-Alive

 

HTTP/1.1 404 Not Found

Server: nginx/1.10.1

Date: Thu, 11 Jan 2018 07:37:30 GMT

Content-Type: text/html; charset=utf-8

Content-Length: 169

Connection: keep-alive

 

<html>

<head><title>404 Not Found</title></head>

<body bgcolor="white">

<center><h1>404 Not Found</h1></center>

<hr><center>nginx/1.10.1</center>

</body>

</html>

**Comment by automatikas** [comment]
Yeah Early morning releases are crazy :)

Found a typo mistake on logBool node, for pingServer action. should be path with `/plugins/` not `/plugin/`

pushed new hotfix release. Try kit 1.0.45.25

Let me know if that helps.

AlarmDB plugin v2.07.5 hotfix

Thanks for the Feedback!!!

Found now strange sedona behavior with buffer been not properly cleared, that does not affect the functionality just gives some rubbish bytes from previous payload on the status and console. Will investigate tonight.

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 11 Jan 2018 08:36:22 GMT
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=20
Set-Cookie: PHPSESSID=silfloaljsegsnts75mj1ofk47; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Access-Control-Allow-Origin: *
Vary: Accept-Encoding

d

{"ping":"ok"}

0

ogged!"}

0
```

**Comment by apexc** [comment]
Hi AJ, 

thanks. 
will test it out later tomorrow. 

just for your info, the link still contain 1.0.45.24 kit.

**Comment by automatikas** [comment]
@apexc 

oh yes tag issues.
redrafted release should be great now.

[v2.07.5](https://github.com/automatikas/AlarmDB-EasyIO/releases/tag/v2.07.5)

Thanks!
