### ISSUE TITLE
Sedona kit ajsoAlarmdb 1.0.45.26 crashing VM of FS32. Use ajsoAlarmdb 1.0.45.25 instead

### ISSUE THREAD

**Issue by automatikas** [automatikas/AlarmDB-EasyIO#26]
There was implemented API response check in 1.0.45.26. It looks like it overflows memory with many alarms triggered.

Symptoms: Sedona restarting.

Downgrade to ajsoAlarmdb 1.0.45.25

**Comment by fwijnands86** [comment]
Had the same issue. Thanks for the info!
