### ISSUE TITLE
Home or back button

### ISSUE THREAD

**Issue by jjwilton** [automatikas/AlarmDB-EasyIO#28]
First of all this alarm database is great. Just one minor addition would make it perfect for us!
When using a touchscreen, we have no way of easily going 'back' or 'home', could you please include an option for this?

I guess the difficulty in creating a 'home' will be that you don't necessicarily know the address. Perhaps a back button is possible?

**Comment by automatikas** [comment]
As default plugin opens in new window so browser back button will not work at all. you could possibly try to modify **[alarmdb/manifest.json](https://github.com/automatikas/AlarmDB-EasyIO/blob/master/alarmdb/manifest.json)** file: **openNewPage** by setting it to false, that should open plugin in the same window then back button of the browser will load previous page you where in no mater if you are on mobile or desktop.

```
{
  "label": "AlarmDB",
  "indexFile": "index.php",
  "enabled": true,
  "openNewPage": false,
  "supportedPlatforms": ["FG", "FG+", "FS", "FW"]
}
```

Thanks for the feedback @jjwilton 
I am closing the issue, feel free to open it again if solution is not working.
