### ISSUE TITLE
AlarmDB doesn't show up

### ISSUE THREAD

**Issue by magiuliani** [automatikas/AlarmDB-EasyIO#33]
I run alarmdb on FS with firmware V3.0b60

- on cpt everything is fine and I push alarm to the db
- on frontend the plugin doesn't show up and I have white page
- if it can be useful, I attached a screenshoot of the error
![errorAlarmDB](https://github.com/automatikas/AlarmDB-EasyIO/assets/5240336/03fa341e-795b-4375-9eaa-71093cb591d1)

**Comment by automatikas** [comment]
Hi, thanks for feedback. Looks like php script does not find settings file. But it could be related to php version or php setting related to latest firmware. I’m on travel now. Will have a look in to it next week.

**Comment by magiuliani** [comment]
Hi,
I want to notice you that the plugin is working. There were some issues on overwriting the controller and I fixed with a factory reset of the controller.
