### ISSUE TITLE
Time stamp issue. controller DB log time zone is UTC not local time

### ISSUE THREAD

**Issue by automatikas** [automatikas/AlarmDB-EasyIO#4]

**Comment by automatikas** [comment]
Time is set now directly at Sedona level from the kit object

**Comment by MantvydasJ** [comment]
Hello, 

Time stamp of alarm acknowledging is not UTC. 
![image](https://user-images.githubusercontent.com/39690133/40779537-0102728a-64de-11e8-90aa-06431ddb9b2c.png)

**Comment by automatikas** [comment]
is it UTC or is not UTC?  From your time and name for me looks correct :) you have +3 from UTC

I see that acknowledge time is UTC but if your controller is set to time zone other than UTC then you will have time zone difference between alarm time and ackn time. that is a bug!

Thanks for feedback!!!

**temporary cheat to fix this:**
_Open **alarmdb_exporter.php** file and edit default time zone to your specific. Find _**line 20**_ comment it out and add new line with your time zone_

```
//date_default_timezone_set('UTC');
date_default_timezone_set('Europe/Vilnius');
```

php time zones: [http://php.net/manual/en/timezones.php](url)

**Comment by MantvydasJ** [comment]
Thank you! Now is working correctly!

**Comment by automatikas** [comment]
Fixed in hotfix release v.2.07.6
Now acknowledge time and new note time will be taken from the user browser not from server. Time and time zone will depend on user computer or mobile time. @MantvydasJ thanks for feedback.
